# Introduction to `NUMPY`

In [1]:
import numpy as np

In [2]:
a = [1, 2,3, 4, 5]

In [3]:
np_a = np.array(a)

In [4]:
np_a

array([1, 2, 3, 4, 5])

In [5]:
np_a ** 2

array([ 1,  4,  9, 16, 25])

In [6]:
a = range(10000000)

In [8]:
%timeit [ i**2 for i in a]

1.99 s ± 6.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
np_a = np.array(a)
%timeit np_a ** 2

3.2 ms ± 48.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
arr1 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
    )

In [11]:
arr1.ndim

2

In [12]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr1.shape

(3, 3)

In [14]:
arr2 = np.array([1, 2, 3])
arr2.ndim

1

In [15]:
arr2.shape

(3,)

In [16]:
# dim   -> number of directions along which numpy is growing 
# shape -> no of elements along every direction 

In [17]:
arr1.shape

(3, 3)

In [18]:
arr3 = np.array(
    [
        [1, 2],
        [4, 5],
        [7, 8]
    ]
    )

In [19]:
arr3.shape

(3, 2)

In [20]:
list(range(1, 5, .5))

TypeError: 'float' object cannot be interpreted as an integer

In [23]:
np.arange(1, 5, .5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [26]:
np.arange(1, 5, 1)

array([1, 2, 3, 4])

In [27]:
type(arr1)

numpy.ndarray

In [28]:
np.array([1, 2.3, 'suman'])

array(['1', '2.3', 'suman'], dtype='<U32')

In [29]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr2[0]

1

In [33]:
arr2

array([1, 2, 3])

In [34]:
arr2[[0,1]]

array([1, 2])

In [35]:
a = [1,2,3,4]

In [37]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [40]:
arr2[[1, 2, 3]]

array([2, 3, 4])

In [41]:
arr2[4:100]

array([ 5,  6,  7,  8,  9, 10])

## Fancy Indexing 

In [42]:
m1 = np.arange(1, 11)

In [43]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
m1 < 6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [46]:
m1[m1 < 6] # using as a mask 

array([1, 2, 3, 4, 5])

In [47]:
m1[m1 % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [48]:
m1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
mask = (m1 % 2 == 0) | (m1 % 5 == 0) 
m1[mask]

array([ 2,  4,  5,  6,  8, 10])

In [58]:
np.arange(4) + 3

array([3, 4, 5, 6])

In [59]:
type(mask)

numpy.ndarray

In [60]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
arr1 * np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [64]:
arr2 * (arr2*10)

array([  10,   40,   90,  160,  250,  360,  490,  640,  810, 1000])

In [65]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr2*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [67]:
a = np.arange(1, 11)

In [68]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
a.sum()

55

In [70]:
a.max()

10

In [71]:
mask

array([False,  True, False,  True,  True,  True, False,  True, False,
        True])

In [72]:
mask = (m1 % 2 == 0) | (m1 % 5 == 0) 


In [73]:
mask

array([False,  True, False,  True,  True,  True, False,  True, False,
        True])

# Assignment

#### Question 1

In [76]:
a = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [77]:
a+1

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [80]:
np.array(list(map(lambda x: x+1, A)))

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [82]:
np.array([x+1 for x in a])

array([ 3,  1,  2, 10,  2,  2,  2,  1,  4,  6])

In [85]:
a.shape

(10,)

In [86]:
a.ndim

1

#### Question 2

In [89]:
def get_array_properties(arr):
    '''
    INPUT: arr -> A nD array
    
    OUTPUT: result -> tuple consisting of shape and dimension
    '''
    
    ## STEP 1. Get the shape of array
    
    shape = arr.shape
    ## STEP 2. Get the dimension of array
    
    dim = arr.ndim
    
    
    return shape,dim

In [90]:
get_array_properties(a)

((10,), 1)

#### Question 3

In [99]:
# Write the code using np.arange() to get all even numbers between 21 and 70, (70 inclusive)

a = np.arange(22, 71, 2)

In [100]:
a

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [102]:
# Write the code using np.arange() to get all odd numbers between 20 and 71. (71 inclusive)

np.arange(21, 72, 2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

#### Question 4

In [109]:
def create_seq(start, end, step):
    '''
    INPUT: start, end, step 
    
    OUTPUT: arr -> 1D numpy array
    
    '''
    
    arr = np.round(np.arange(start, end, step), 2)
    
    return arr

In [110]:
create_seq(5, 7, .5)

array([5. , 5.5, 6. , 6.5])

#### Question 5

In [120]:
def seq(start, length, step):
    ''' start, length and step are in form of integers all representing the attributes as their names suggest
        output -> A numpy array is expected to be returned'''

    # YOUR CODE GOES HERE
    end = length*step + start
    sequence = np.arange(start, end, step)
    
    return sequence

In [121]:
seq(5, 10, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [122]:
seq(10, 10, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### Question 6

In [157]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])

In [154]:
x

array([-5,  9, 20, 25, -3,  5, 16, 10, -8])

In [158]:
mask = (x >= -5) & (x <= 15)

In [160]:
x[mask]

array([-5,  9, -3,  5, 10])

In [161]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1 

In [162]:
x

array([  5,  -9,  20,  25,   3,  -5,  16, -10,  -8])

In [138]:
a

array([-5, -3,  5])

In [144]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
np.sort(x)

array([-8, -5, -3,  5,  9, 10, 16, 20, 25])

#### Question 7

In [163]:
def update_height(height,delta):

    height = np.array(height)

    delta = np.array(delta)

    new_height = height+delta 

    return new_height

In [164]:
def update_height2(height, delta):

    new_height=[]

    for i in range(len(height)):

        new_height.append(height[i]+delta[i])

    return new_height

In [165]:
height = np.arange(100000)
delta = height * .02

In [166]:
%timeit update_height(height,delta)

121 µs ± 306 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [167]:
height = range(100000)
delta = [.1] * 100000

In [168]:
%timeit update_height2(height,delta)

13.3 ms ± 30.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### Question 9

In [169]:
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))


['Astha' 'Raghavendra' 'Ram']


In [170]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [180]:
import numpy as np
def mse(A,B):
    '''A,B -> Numpy arrays
       output -> A float rounded up to 2 decimal points should be returned'''
    
    ### STEP 1. Calculate difference between elements of A and B
    
    diff = A - B
    
    ## STEP 2: Take square of difference
    
    sq_diff = diff ** 2
    
    ## STEP3 : Take mean of squared difference
    
    mean_sq_diff = sq_diff.sum() / len(diff)
    
    ## STEP 4 : Round off values to 2 decimal places.
    
    mean_sq_diff = np.round(mean_sq_diff, 2)
    
    return mean_sq_diff

In [181]:
a = np.array([1,1,2,2,4])
b = np.array([0.6,1.29,1.99,2.69,3.4])
mse(a, b)

0.22

In [174]:
diff = a - b

In [175]:
diff

array([ 0.4 , -0.29,  0.01, -0.69,  0.6 ])

In [176]:
diff ** 2

array([1.600e-01, 8.410e-02, 1.000e-04, 4.761e-01, 3.600e-01])

In [178]:
sum(diff ** 2) / len(a)

0.21606

In [179]:
len(a)

5

#### Question 10

In [202]:
import numpy as np

def calculate_mean_age(birds, age):
    '''
    INPUT: birds, age -> 1D array
    
    OUPUT: mean_age -> float variable
    '''
    np_birds = np.array(birds)
    np_age = np.array(age)
    
    mean_age = None
    
    ## STEP1. Create mask to get Crane birds from birds array
    mask = np.where(np_birds == 'Cranes')[0]
    
    ## STEP2. Get the age of crane birds
    
    crane_ages = np_age[mask]
    
    ## STEP 3. Calculate mean age of crane birds
    
    mean_age = crane_ages.mean()
    
    ## STEP 4. Round off the mean age to 2 decimal points
    
    mean_age = np.round(mean_age, 2)
    
    
    return mean_age

In [220]:
import numpy as np

def calculate_mean_age2(birds, age):
    '''
    INPUT: birds, age -> 1D array
    
    OUPUT: mean_age -> float variable
    '''
    np_birds = np.array(birds)
    np_age = np.array(age)
    
    mean_age = None
    
    ## STEP1. Create mask to get Crane birds from birds array
    mask = (np_birds == 'Cranes')
    
    ## STEP2. Get the age of crane birds
    
    crane_ages = np_age[mask]
    
    ## STEP 3. Calculate mean age of crane birds
    
    mean_age = crane_ages.mean()
    
    ## STEP 4. Round off the mean age to 2 decimal points
    
    mean_age = np.round(mean_age, 2)
    
    
    return mean_age

In [219]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [221]:
calculate_mean_age2(birds, age)

4.75

In [222]:
calculate_mean_age(birds, age)

4.75