In [3]:
import pandas as pd

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
arr1 = np.array([1,2,3,4])
num = 4
acc = 0

In [7]:
arr1+num

array([5, 6, 7, 8])

In [8]:
a

array([5, 6, 7, 8])

In [9]:
arr1

array([1, 2, 3, 4])

In [10]:
for i in arr1:
    num += arr1

In [11]:
arr1

array([1, 2, 3, 4])

In [12]:
num

array([ 8, 12, 16, 20])

In [13]:
arr1 = np.array([1,2,3,4])
num = 4
acc = 0

In [14]:
for i in arr1:
    num += arr1
    print(num)

[5 6 7 8]
[ 6  8 10 12]
[ 7 10 13 16]
[ 8 12 16 20]


In [15]:
arr1 = np.array([1,2,3,4])
num = 4
acc = 0

np.sum(arr1) +num

14

In [16]:

# Create a dictionary with the column names as keys and the data as values
data = {
    'name': ['Nikhil', 'Ram', 'Alice'],
    'username': ['nik123', 'itsramhere', 'alice789'],
    'id': [1, 2, 3]
}

# Create the DataFrame
df = pd.DataFrame(data)

In [18]:
df

name    username  id
0  Nikhil      nik123   1
1     Ram  itsramhere   2
2   Alice    alice789   3

In [20]:
df.apply(lambda x: check(x['name'],x['username']), axis=1)

0    False
1     True
2     True
dtype: bool

In [21]:
def check(n, u):
    return n.lower() in u

df[~(df.apply(lambda x: check(x['name'],x['username']), axis=1))]['id']

0    1
Name: id, dtype: int64

In [22]:
arr1 = np.ones((15, 1, 3))
arr1

array([[[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]],

       [[1., 1., 1.]]])

In [24]:
arr2 = 4 * np.ones((3, 1))
arr2

array([[4.],
       [4.],
       [4.]])

In [25]:
arr1 +arr2

array([[[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[5., 5., 5.],
        [5., 5., 5.],
    

In [26]:
a = arr1 +arr2
a.shape

(15, 3, 3)

In [27]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [28]:
a*a

array([ 0,  1,  4,  9, 16])

In [29]:
a**a

array([  1,   1,   4,  27, 256])

In [34]:
aa = np.vectorize(np.square(a))
aa(a)

TypeError: 'numpy.ndarray' object is not callable

In [31]:
np.square(a)

array([ 0,  1,  4,  9, 16])

In [32]:
np.array([i*i for i in a])

array([ 0,  1,  4,  9, 16])

In [33]:
a

array([0, 1, 2, 3, 4])

In [40]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
np.split(arr, [1, 3], axis=1)[1].shape

(3, 2)

In [45]:
np.split(arr, [1, 3], axis=1)[1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
np.split(arr, [1, 3], axis=1)[1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [48]:
data = {
    'Name': ['John', 'Jane', 'Alice', 'Bob', 'Emily'],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'Professions': ['Engineer', 'Doctor', 'Teacher', 'Lawyer', 'Artist']
}

df = pd.DataFrame(data)

In [49]:
df

Name  Gender Professions
0   John    Male    Engineer
1   Jane  Female      Doctor
2  Alice  Female     Teacher
3    Bob    Male      Lawyer
4  Emily  Female      Artist

In [52]:
df.iloc[:2, :10]

Name  Gender Professions
0  John    Male    Engineer
1  Jane  Female      Doctor

In [51]:
df.loc[:2, "Name":"Professions"]

Name  Gender Professions
0   John    Male    Engineer
1   Jane  Female      Doctor
2  Alice  Female     Teacher

In [71]:
df = pd.read_csv('https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/033/328/original/mpg.csv')

In [72]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name  
0            70     usa  chevrolet chevelle malibu  
1            70     usa          buick skylark 320  
2            70     usa         plymouth satellite  
3            70     usa              amc rebel sst  
4            70     usa                ford torino  
..          ...     ...                        ...  
393          82     usa            ford mustang gl  
394          82  europe                  vw pickup  
395          82     usa              dodge rampage  
396          82     usa                ford ranger  
397          82     usa                 chevy s-10  

[398 rows x 9 columns]

In [74]:
df[df['origin'] == 'europe'].sort_values('cylinders', ascending=False)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
360  30.7          6         145.0        76.0    3160          19.6   
277  16.2          6         163.0       133.0    3410          15.8   
211  16.5          6         168.0       120.0    3820          16.7   
275  17.0          6         163.0       125.0    3140          13.6   
297  25.4          5         183.0        77.0    3530          20.1   
..    ...        ...           ...         ...     ...           ...   
177  23.0          4         115.0        95.0    2694          15.0   
178  23.0          4         120.0        88.0    2957          17.0   
179  22.0          4         121.0        98.0    2945          14.5   
180  25.0          4         121.0       115.0    2671          13.5   
394  44.0          4          97.0        52.0    2130          24.6   

     model_year  origin                name  
360          81  europe        volvo diesel  
277          78  europe       peugeot 604sl  
211          76  europe  mercedes-benz 280s  
275          78  europe         volvo 264gl  
297          79  europe  mercedes benz 300d  
..          ...     ...                 ...  
177          75  europe          audi 100ls  
178          75  europe         peugeot 504  
179          75  europe         volvo 244dl  
180          75  europe           saab 99le  
394          82  europe           vw pickup  

[70 rows x 9 columns]

In [75]:
df2 = df[df['origin'] == 'europe'].sort_values('cylinders', ascending=False)

In [78]:
df2['cylinders'].value_counts()

4    63
6     4
5     3
Name: cylinders, dtype: int64

In [82]:
def func(x, y):
    return (y-x)**2 

In [83]:
res = np.vectorize(func)

In [89]:
print(res(np.array([1,2,3]), np.array([4,5,6])).reshape(3, -1).T)

[[9 9 9]]
