# Linear Regression 

### Q4. Calculate the loss value


In [20]:
import numpy as np
def cost(x, y, w):

    x = np.asarray(x)
    w = np.asarray(w)
    y = np.asarray(y)

    n = len(y)
    loss = (1 / (2* n)) * (np.sum((y - np.dot(x, w))**2)) 

    #YOUR CODE GOES HERE

    
    return round(loss, 2)

In [21]:
x = [[1.0, 0.0], [1.0, 1.0], [1.0, 2.0], [1.0, 3.0], [1.0, 4.0], [1.0, 5.0], [1.0, 6.0], [1.0, 7.0], [1.0, 8.0], [1.0, 9.0]]
y = [32.69, 30.56, 32.04, 32.27, 35.98, 34.39, 40.25, 39.24, 37.14, 39.38]
w = [30.0, 1.0]

In [22]:
cost(x, y, w)

1.81

In [6]:
x = np.asarray(x)
w = np.asarray(w)
y = np.asarray(y)

In [7]:
x.shape

(10, 2)

In [8]:
w.shape

(2,)

In [9]:
np.dot(x, w)

array([30., 31., 32., 33., 34., 35., 36., 37., 38., 39.])

In [10]:
x.dot(w)

array([30., 31., 32., 33., 34., 35., 36., 37., 38., 39.])

### Q5. Updated values of weights


In [24]:
import numpy as np

def gradient_descent(x, y, w, alpha, nitr):

    x = np.asarray(x)
    y = np.asarray(y)
    w = np.asarray(w)

    n = len(y)
    xTrans = x.transpose()
    #Perform Gradient descent on data nitr times
    for i in range(0, nitr):
        # calculate the output of y_pred using weights
        y_pred = np.dot(x, w)

        # Calculate the difference between y_pred and y
        loss = y_pred - y

        #average the gradient
        gradient = np.dot(xTrans, loss) / n

        #Update the weights
        w = w - alpha * gradient

        #round off the values in array to two decimal places
        
    return np.round(w,2)

In [25]:
x = [[1.0, 0.0], [1.0, 1.0], [1.0, 2.0], [1.0, 3.0], [1.0, 4.0], [1.0, 5.0], [1.0, 6.0], [1.0, 7.0], [1.0, 8.0], [1.0, 9.0]]
y = [26.75, 29.12, 36.46, 32.82, 30.46, 39.7, 35.52, 39.84, 36.83, 42.74]
w = [1.0, 1.0]
alpha = 0.0005
nitr = 10

In [28]:
x = [[8,3], [2,9]]
y = [1, 0]
w = [1, 3]
lr = 0.01
nitr = 10

In [29]:
gradient_descent(x, y, w, alpha, nitr)

array([0.6 , 2.32])

In [1]:
x = [[1.0, 0.0], [1.0, 1.0], [1.0, 2.0], [1.0, 3.0], [1.0, 4.0], [1.0, 5.0], [1.0, 6.0], [1.0, 7.0], [1.0, 8.0], [1.0, 9.0]]


In [3]:
x = np.asarray(x)

In [4]:
x.T

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [7]:
import numpy as np

def updated_weights(X, y, w, lr):
    """ 
    X is a 2d list representing the values of the variables for different observations
    y is the actual output for the observations
    w is the coefficient vector
    lr is the learning rate
    """
    
    X = np.asarray(X)
    y = np.asarray(y)
    w = np.asarray(w)
    
    XTrans = X.T
    
    for _ in range(10): # 10 iterations of gradient descent
        y_pred = np.dot(X, w)
        loss = y_pred - y
        
        grad = np.dot(XTrans, loss)
        w = w - lr * grad

    w = np.round(w, 2)
    return w


In [17]:
x = [[8,3], [2,9]]
y = [1, 0]
w = [1, 3]
lr = 0.01

updated_weights(x, y, w, lr)

array([ 0.12, -0.02])

In [14]:
import numpy as np

def updated_weights(X, y, w, lr):
    # X is a 2d list representing the values of the variables for different observations
    # y is the actual output for the observations
    # w is the coefficient vector
    # lr is the learning rate
    X = np.asarray(X)
    y = np.asarray(y)
    w = np.asarray(w)
    
    for _ in range(10): # 10 iterations of gradient descent
        gradient = np.dot(X.T, (np.dot(X, w) - y))
        w = w - lr * gradient
    
    # rounding off to two decimal places
    w = np.round(w, 2)
    
    return w


In [19]:
x = [[8,3], [2,9]]
y = [[1], [0]]
w = [1, 3]
lr = 0.01

updated_weights(x, y, w, lr)

array([[ 0.14,  0.14],
       [-0.03, -0.03]])

In [20]:
y

[[1], [0]]

In [21]:
y = np.asarray(y)

In [22]:
y.reva

array([[1],
       [0]])

In [23]:
import numpy as np
y = np.array([[1], [0]])
y_flat = y.ravel()


# Module Exam

In [1]:
import numpy as np

## Q1

In [4]:
import numpy as np
def calc_r2(y_true, y_pred):
    
    y_true = np.asarray(y_true)
    y_pred = np.asarray(y_pred)
   
    
    #Calculate total sum of squares
    res_ss = np.sum((y_pred - y_true)**2)
    
    #Calculate residual sum of squares
    y_mean = np.mean(y_true)
    tot_ss = np.sum((y_mean - y_true)**2)
    
    #Calculate r2
    r2 = 1 - (res_ss / tot_ss)
    
    return r2.round(2)

## Q2

In [2]:
def calculate_classification_metrics(sensitivity, specificity):
    P = 1
    N = 1 
    # Calculate True Positive (TP) and False Negative (FN) using Sensitivity
    TP = sensitivity * P 
    FN = P - TP
    
    # Calculate True Negative (TN) and False Positive (FP) using Specificity
    TN = specificity * N
    FP = N - TN
    
    
    ## DO NOT CHANGE THE return STATEMENT
    
    return round(TP,2), round(FP,2), round(TN,2), round(FN,2)

## Q3

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split  
    
def train(X,Y):

    # Split dataset into training set and test set
    x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) # 80% training and 20% test


    #INITIALIZE classifier
    classifier = LogisticRegression(random_state=42)


    #TRAIN CLASSIFIER
    classifier.fit(x_train, y_train)

    # Return ACCURACY FOR test data
    acc = classifier.score(x_test, y_test)
    coef = classifier.coef_.round(2)
    intercept = classifier.intercept_.round(2)

    return round(acc,2), coef, intercept